app_home:
   path: /
   controller: App\Controller\HomeController::index

app_register:
    path: /inscription
    controller: App\Controller\RegisterController::index

app_login:
    path: /connexion
    controller: App\Controller\SecurityController::login

app_logout:
    path: /deconnexion
    controller: App\Controller\SecurityController::logout

app_account:
    path: /compte
    controller: App\Controller\AccountController::index

app_account_password:
    path: /compte/update-password
    controller: App\Controller\AccountPasswordController::index

app_admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

app_products:
    path: /nos-produits
    controller: App\Controller\ProductController::index